services:
  migrate:
    build: .
    depends_on:
      - db
    env_file:
      - .env-non-dev
    command: >
      sh -c "apt-get update && apt-get install -y netcat &&
             until nc -z db 5432; do echo 'waiting for db'; sleep 1; done;
             alembic upgrade head"

  web:
    build: .
    container_name: web
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env-non-dev
    command: >
      sh -c "apt-get update && apt-get install -y netcat &&
             until nc -z db 5432; do echo 'waiting for db'; sleep 1; done;
             uvicorn main:app --host 0.0.0.0 --port 8000"

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    env_file:
      - .env-non-dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
